config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
  get 'users/:user_id/posts_list', to: 'api#list_all_user_posts', as: :list_all_user_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_users_and_post_comments', as: :list_users_and_post_comments
  post 'users/:user_id/posts/:post_id/add_comment', to: 'api#add_comment', as: :add_comment
  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :likesCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def update_posts_counter
    user.increment!(:postsCounter)
  end

  def recent_comments()
    comments.last(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = @user = User.includes(posts: %i[comments likes]).find_by(id: params[:user_id])
    @post = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comment = @post.comments
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    @post.user = @user

    if @post.user
      redirect_to user_posts_path(@user, @post), notice: 'Post was successfully created!'
    else
      render :new
      flash[:alert] = 'Failed to create a post!'
    end
  end

  def destroy
    @user = User.find(params[:user_id]) # current_user
    post = Post.find(params[:id])

    if post.destroy
      flash[:success] = 'Post deleted successfully'
      redirect_to user_posts_path(@user)
    else
      flash.now[:error] = 'Error: Post could not be deleted'
      redirect_to user_post_path(@user, post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<section class="comment-container">
<div class='comm-card'>
<h1 class="mx-auto mt-5 w-25">New Post</h1>
<%= form_with(model: post, url: { action: "create" }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> Unable to save this post</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class='input-container'>
<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "comment-form-2" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, class: "comment-form-2"%>
  </div>

  <div class="actions">
    <%= form.submit class: "see-all"%>
  </div>
</div>
  
<% end %>
</div>
</section>

app/views/posts/index.html.erb
<section class="user-details">
<section class='user-section-card'>
<div class="user-img"><img src="<%= @user.photo %>" alt="user_photo"></div>
  <div class="user-card">
    <div class="user-card__name">
    <h1><%= @user.name %><h1>
    </div>
    <div class="user-card__email">
    <p>Number of posts:<%= @user.posts.length %> </p>  
  </div>
</section>
   
<% @post.each do |post| %>
  <%# <%= link_to user_post_path(@user.id,post.id),  class: "post-p" do %> 
    <section class='user-section-card'>
        <div class="user-card comment-card">
          <div class="user-card__name">
          <%= link_to user_post_path(@user.id,post.id),  class: "post-p" do %> 
            <%= post.text %>
          <% end %>
            <h3>Comments</h3>
            <% post.user.comments.each do |comment| %>
              <h4>Comment# <%= comment.id %>:<%= comment.text %></h4>
              <% if can? :destroy, comment %>
                <%= form_with url: user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <button class="custom-button">Delete</button> 
                <% end %> 
              <% end %>
            <% end %>
          </div>
          <div class="comment__like">
            <p>Comments : <%= @user.comments.length %> </p>  
            <p>Likes:<%= @user.likes.length %> </p> 
          </div>
          <div class="actions">
          <% if can? :destroy, post %>
            <%= form_with url: user_post_path(@user, post), method: :delete do %>
              <button class="custom-button">Delete</button>
            <% end %>
          <% end %>
            <%= link_to new_user_post_comment_path(@user, post) do %>
              <button class="custom-button">Comment</button>
            <% end %>
            <%= button_to 'Like', user_post_likes_path(@user, post), method: :post, class: 'see-all'%>
        </div>
      <div>
    </section>
<% end %>
 <%= link_to 'Create new post', new_user_post_path(@user.id), class: "see-all" %> 
 <p class="copy-right">© 2022 GitHub, Inc. Terms</p>
</section>

app/views/posts/new.html.erb

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<section class="user-details">
<section class='user-section-card'>
<div class="user-img"><h3>Post #<%= @post.id %> By <%= @user.name %></h3></div>
  <div class="user-card">
    <div class="user-card__name">
    <h1>Comments <%= @post.comments.length %><h1>
    </div>
    <div class="user-card__email">
    <p>Likes:<%= @post.likes.length %> </p>  
  </div>
</section>

<div class='user-section-card'><%= @post.text %></div>

<div class='user-section-card comment-owner'>
<% @post.user.comments.each do |comm| %>
  <p class='list-comment'><%= @user.name %> : <%= comm.text %></p>
<% end %>
</div>
<div class='btn-container'>
<%= link_to 'Add a comment', new_user_post_comment_path(@user.id, @post.id), class: "see-all" %> 
<%= button_to 'Like', user_post_likes_path(@user, @post), method: :post, class: 'see-all'%>
</div>
 <p class="copy-right">© 2022 GitHub, Inc. Terms</p>
</section>